In [1]:
a = 1
b = a
a = 2
print(b)

1


In [2]:
class Int():
    def __init__(self) -> None:
        self.a = 1

old = Int()
new = old
old.a = 2
print(new.a)

2


In [1]:
import torch

In [2]:
a = torch.Tensor([[1, 2], [3, 4]]).reshape((1, -1)).squeeze()
a

tensor([1., 2., 3., 4.])

In [3]:
b = torch.Tensor([1, 2])
b

tensor([1., 2.])

In [4]:
c = torch.cat([a, b])
c

tensor([1., 2., 3., 4., 1., 2.])

In [5]:
d = torch.unsqueeze(c, dim=0)
d

tensor([[1., 2., 3., 4., 1., 2.]])

In [19]:
torch.softmax(c, dim=-1)

tensor([0.0286, 0.0779, 0.2117, 0.5753, 0.0286, 0.0779])

In [6]:
from model import MLP
d

tensor([[1., 2., 3., 4., 1., 2.]])

In [7]:
net = MLP(6, 10)
net(c)

tensor([0.1212, 0.1425, 0.0898, 0.0000, 0.2165, 0.0000, 0.0525, 0.0000, 0.0000,
        0.0559], grad_fn=<ReluBackward0>)

In [9]:
res = net(c)
res

tensor([0.1212, 0.1425, 0.0898, 0.0000, 0.2165, 0.0000, 0.0525, 0.0000, 0.0000,
        0.0559], grad_fn=<ReluBackward0>)

In [10]:
torch.softmax(res, dim=0)

tensor([0.1052, 0.1075, 0.1020, 0.0932, 0.1157, 0.0932, 0.0982, 0.0932, 0.0932,
        0.0986], grad_fn=<SoftmaxBackward0>)

In [17]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])
c = torch.Tensor([7, 8, 9])
torch.stack((a, b, c), dim=0)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [18]:
torch.Tensor((1, 2, 3))

tensor([1., 2., 3.])